### ISSUE TITLE
`direction: rtl` in filenames list causes leading-period to misrender

### ISSUE THREAD

**Issue by TBBle** [cyber-dojo/web#19]
The `direction: rtl` in the CSS file at https://github.com/cyber-dojo/web/blob/30fe5a4e0128f7b156d89c6442910cb6607a4afb/app/assets/stylesheets/cyber-dojo.css.scss#L77 causes files with a leading '.' to have the '.' render at the end, and vice-versa.

Noticed while messing around with cyber-dojo/start-points-languages#5

**Comment by JonJagger** [comment]
Good spot. I will investigate. Thanks

**Comment by JonJagger** [comment]
Removed the rtl 
dot files now render correctly on http://cyber-dojo.org
Thanks
