### ISSUE TITLE
SpecFlow: incomplete feature file removal

### ISSUE THREAD

**Issue by szabopeter** [cyber-dojo/web#37]
After removing the sample feature file and step definitions, its tests are still executed. Maybe the .feature.cs files are not removed?
Example:
http://cyber-dojo.org/review/show/A80C07458B?avatar=bat&was_tag=8&now_tag=9

HikerSpec.feature and HikerSteps.cs are removed, but the output shows that the code generated from the HikerSpec.feature (ASimpleSpecificationToStartYouOffFeature) is still used and of course, failing.

**Comment by szabopeter** [comment]
Added an 'rm *.feature.cs' line to cyber-dojo.sh, right before the 'code-behind' generation solved the problem.

**Comment by JonJagger** [comment]
Good catch. I've made the change in
https://github.com/cyber-dojo-languages/csharp-specflow
It will appear on cyber-dojo.org in the next few days.
Thanks
