### ISSUE TITLE
cyber-dojo.org doesn't work in Safari because of keyword `let`

### ISSUE THREAD

**Issue by Quuxplusone** [cyber-dojo/web#39]
[Function `cyberDojo` contains the word `let`](https://github.com/cyber-dojo/web/blob/12d49411555b60a9737792a21e3b73cad827b50e/app/assets/javascripts/cyber-dojo_hover_tips.js#L6), which isn't supported on Safari.
https://stackoverflow.com/questions/34636737/unexpected-use-of-reserved-word-let-in-strict-mode

The visible symptom is that if you visit http://cyber-dojo.org in Safari, the whole page loads, but none of the hyperlinks work. I click them, and nothing happens. (I assume this is because the Javascript that's supposed to hook them up to actions has not been run because of the above syntax error.)

Is it possible to use the word `var` instead of `let` (for example)?

**Comment by JonJagger** [comment]
Good spot. Thankyou. Fixed now.
