### ISSUE TITLE
Make syntax highlighting toggleable

### ISSUE THREAD

**Issue by byran** [cyber-dojo/web#43]
Add a toggle syntax highlighting button to the options dialog
This can be accomplished by switching CodeMirror's theme to a "null" theme

**Comment by JonJagger** [comment]
I've moved the [id,display_name,exercise] info onto the long footer.
This frees up the 'options' dialog to just hold:
o) syntax-highlighting on-off toggle
o) line-numbers on-off toggle
o) maybe info on keyboard shortcuts
