### ISSUE TITLE
Predict buttons now disappear after you press them

### ISSUE THREAD

**Issue by jjwils** [cyber-dojo/web#87]
This seems to be a recent change.  In predict mode when you make a prediction (red, yellow, green), the buttons collapse every time, which is not great for UX.  Same behaviour on safari and chrome.

**Comment by JonJagger** [comment]
Confirmed this is a bug.
Thank you for reporting it.

**Comment by JonJagger** [comment]
Yes related.
Also fixed in https://github.com/cyber-dojo/saver/commit/f58006861bdd79dda20e43be60b33e2083835181
Thanks again.
